default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: vignere_development
  username: marilynmarquez
  password: postgres
  host: localhost

test:
  <<: *default
  database: vignere_test
  username: marilynmarquez
  password: postgres
  host: localhost

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
